[package]
name = "zeus-bip32"
description = "BIP32 Key Derivation"
readme = "readme.md"
repository = "https://github.com/greekfetacheese/zeus/tree/master/crates/zeus-bip32"
version = "0.1.2"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
sha2 = "0.10"
hmac = "0.12"
ripemd = "0.1"
k256 = "0.13"
secure-types = "0.3"
thiserror = "2"
serde = { version = "1", optional = true, features = ["derive"] }

[dev-dependencies]
hex = "0.4"

[features]
serde = ["dep:serde", "secure-types/serde"]
