[package]
name = "currency"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../abi" }
utils = { path = "../utils" }
types = { path = "../types" }


tokio = {version = "1.43.0", features = ["rt-multi-thread"]}
serde = "1.0.217"
anyhow = "1.0.95"

[dev-dependencies]
url = "2"