[workspace]
resolver = "2"
members = ["crates/ncrypt", "crates/egui-theme", "crates/zeus-token-list", "crates/zeus-eth"]

[package]
name = "zeus-desktop"
authors = ["Michalis Molfetas"]
version = "0.1.0"
edition = "2021"
default-run = "zeus-desktop"

[dependencies]

# GUI
eframe = {version = "0.31.0", features = ["wgpu"]}
egui = {version = "0.31.0", features = ["serde"]}
egui_extras = {version = "0.31.0", features = ["svg", "image"]}
egui-theme = { path = "crates/egui-theme" }
image = "0.25.1"


# Eth
zeus-eth = { path = "crates/zeus-eth" }
zeus-token-list = { path = "crates/zeus-token-list" }


# Alloy
alloy-transport-http = {version = "=0.9.2", features = ["reqwest"]}
alloy-signer = "0.11.0"
alloy-signer-local = "0.11.0"

# Crypto
ncrypt = { path = "crates/ncrypt" }

# Tracing
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter", "fmt"]}
tracing-appender = "0.2.3"

# Async
tokio = { version = "1.35.1", features = ["rt"] }
futures = "0.3.31"
reqwest = "0.12.9"


# Misc
anyhow = "1.0.44"
serde = "1.0.203"
serde_json = "1.0.117"
lazy_static = "1.4.0"

[profile.dev]
lto = "off"
incremental = true
opt-level = 1
debug = false

[features]
default = []