[workspace]
resolver = "2"
members = ["crates/egui-theme", "crates/zeus-token-list", "crates/zeus-eth", "crates/egui-widgets", "crates/tests"]

[package]
name = "zeus"
authors = ["Michalis Molfetas"]
version = "0.1.0"
edition = "2021"
default-run = "zeus"

[dependencies]

# GUI
eframe = {version = "0.32.0", features = ["wgpu"]}
egui = {version = "0.32.0", features = ["serde"]}
egui_extras = {version = "0.32.0", features = ["image"]}
egui-widgets = {path = "crates/egui-widgets"}
image = "0.25.1"
wgpu = "25"


# Zeus Crates
zeus-eth = { path = "crates/zeus-eth" }
zeus-token-list = { path = "crates/zeus-token-list" }
egui-theme = { path = "crates/egui-theme" }


# Alloy
alloy-consensus = "1"
alloy-signer = {version = "1", features = ["eip712"]}
alloy-signer-local = {version = "1", features = ["mnemonic"]}
alloy-network = "1"
alloy-dyn-abi = {version = "1", features = ["eip712"]}

# Encryption
ncrypt-me = { git = "https://github.com/greekfetacheese/ncrypt-me.git", branch = "master" }

# Memory
secure-types = {git = "https://github.com/greekfetacheese/secure-types.git", branch = "master"}


# Tracing
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter", "fmt"]}
tracing-appender = "0.2.3"

# Async
tokio = { version = "1.35.1", features = ["full"] }
warp = "0.3.7"
futures = "0.3.31"


# Misc
anyhow = "1.0.44"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
lazy_static = "1.4.0"
bincode = "2"

[profile.prod]
inherits = "release"
codegen-units = 32
incremental = true
panic = "abort"
strip = true
# Slightly smaller binary size than level 3
opt-level = 2
debug = false
lto = "fat"

[profile.dev]
lto = "off"
incremental = true
opt-level = 1
debug = true


[features]
dev = []
