[workspace]
resolver = "2"
members = ["crates/egui-theme", "crates/zeus-token-list", "crates/zeus-eth"]

[package]
name = "zeus-desktop"
authors = ["Michalis Molfetas"]
version = "0.1.0"
edition = "2021"
default-run = "zeus-desktop"

[dependencies]

# GUI
eframe = {version = "0.31.0", features = ["wgpu"]}
egui = {version = "0.31.0", features = ["serde"]}
egui_extras = {version = "0.31.0", features = ["svg", "image"]}
egui-theme = { path = "crates/egui-theme" }
image = "0.25.1"


# Eth
zeus-eth = { path = "crates/zeus-eth" }
zeus-token-list = { path = "crates/zeus-token-list" }


# Alloy
alloy-signer = "=0.11.1"
alloy-signer-local = "=0.11.1"
alloy-network = "=0.11.1"

# Crypto
ncrypt-me = { git = "https://github.com/greekfetacheese/ncrypt-me.git", branch = "master" }
chacha20poly1305 = "0.10.1"

# Tracing
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter", "fmt"]}
tracing-appender = "0.2.3"

# Async
tokio = { version = "1.35.1", features = ["rt"] }
futures = "0.3.31"



# Misc
anyhow = "1.0.44"
serde = "1.0.203"
serde_json = "1.0.117"
lazy_static = "1.4.0"

[profile.maxperf]
inherits = "release"
codegen-units = 1
strip = true
opt-level = 2
debug = false
lto = "fat"
panic = "abort"

[profile.dev]
lto = "off"
incremental = true
opt-level = 1
debug = true

[[bin]]
name = "dump_test"
path = "src/bin/dump_test.rs"

[features]
default = []