[workspace]
resolver = "2"
members = ["crates/egui-theme", "crates/zeus-token-list", "crates/zeus-eth", "crates/egui-widgets", "crates/tests"]

[package]
name = "zeus"
authors = ["Michalis Molfetas"]
version = "0.1.0"
edition = "2024"
default-run = "zeus"



[dependencies]

# GUI
eframe = {version = "0.32.0", features = ["wgpu"]}
egui = {version = "0.32.0", features = ["serde"]}
egui_extras = {version = "0.32.0", features = ["image"]}
egui-widgets = {path = "crates/egui-widgets"}
image = "0.25.1"
wgpu = "25"


# Zeus Crates
zeus-eth = { path = "crates/zeus-eth" }
zeus-token-list = { path = "crates/zeus-token-list" }
egui-theme = { path = "crates/egui-theme", features = ["serde"]}

# Alloy
alloy-consensus = "1"
alloy-signer-local = {version = "1", features = ["mnemonic"]}


# Crypto
sha3 = "0.10.8"
sha2 = "0.10.9"
hmac = "0.12.1"
ripemd = "0.1.3"
rand = "0.8"

# Make sure zeroize is enabled
generic-array = {version = "1", features = ["zeroize"]}

# Encryption
ncrypt-me = "0.1"

# Memory
secure-types = "0.1"


# Tracing
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter", "fmt"]}
tracing-appender = "0.2"

# Async
tokio = { version = "1", features = ["rt-multi-thread"] }
warp = "0.3.7"
futures = "0.3"
reqwest = { version = "0.12", features = ["json"] }


# Misc
anyhow = "1"
thiserror = "2"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
lazy_static = "1.4"
bincode = "2"

[profile.prod]
inherits = "release"
codegen-units = 32
incremental = true
strip = true
# Slightly smaller binary size than level 3
opt-level = 2
debug = false
lto = "fat"

[profile.dev]
lto = "off"
incremental = true
opt-level = 1
debug = true


[features]
dev = []

[lints.clippy]
new_without_default = "allow"
too_many_arguments = "allow"
unnecessary_unwrap = "allow"
needless_return = "allow"
needless_borrow = "deny"
