[package]
name = "egui-theme"
authors = ["Michalis Molfetas"]
version = "0.1.0"
edition = "2021"

[dependencies]
egui = {version = "0.31.0", features = ["serde"]}
serde_json = "1.0.135"
serde = { version = "1.0.217", features = ["derive"] }