[package]
name = "abi"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-sol-types = {version = "0.8.20", features = ["json"]}
alloy-primitives = "0.8.20"

alloy-rpc-types = "=0.9.2"
alloy-contract = "=0.9.2"
alloy-provider = "=0.9.2"
alloy-transport = "=0.9.2"

anyhow = "1.0.95"