[package]
name = "abi"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-sol-types = {version = "1", features = ["json"]}
alloy-primitives = "1.1.0"

alloy-rpc-types = "1.0.3"
alloy-contract = "1.0.3"
alloy-provider = "1.0.3"

anyhow = "1.0.95"
serde = "1.0.217"