[package]
name = "abi"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-sol-types = {version = "0.8.20", features = ["json"]}
alloy-primitives = "0.8.20"

alloy-rpc-types = "0.12.6"
alloy-contract = "0.12.6"
alloy-provider = "0.12.6"

anyhow = "1.0.95"