[package]
name = "abi"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-sol-types = {version = "1", features = ["json"]}
alloy-primitives = "1.3.0"

alloy-rpc-types = "1"
alloy-contract = "1"
alloy-provider = "1"

anyhow = "1"
serde = "1"