[package]
name = "wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
zeroize = "1.8.1"
alloy-signer-local = "=0.11.1"
alloy-network = "=0.11.1"
alloy-primitives = "0.8.20"

serde = "1.0.217"
serde_json = "1.0.138"
secure-types = {git = "https://github.com/greekfetacheese/secure-types.git", branch = "master", features = ["serde"]}
memsec = "0.7.0"