[package]
name = "zeus-eth"
version = "0.1.0"
edition = "2021"

[dependencies]
# Local Crates
abi = { path = "crates/abi"}
amm = { path = "crates/amm"}
currency = { path = "crates/currency"}
revm-utils = { path = "crates/revm-utils", optional = true}
types = { path = "crates/types"}
utils = { path = "crates/utils" , optional = true}
wallet = { path = "crates/wallet", optional = true}




[features]
utils = ["dep:utils"]
wallet = ["dep:wallet"]
revm-utils = ["dep:revm-utils"]