members = ["crates/*"]
resolver = "2"

[package]
name = "zeus-eth"
version = "0.1.0"
edition = "2021"

[dependencies]
# Local Crates
abi = { path = "crates/abi"}
amm = { path = "crates/amm"}
currency = { path = "crates/currency"}
revm-utils = { path = "crates/revm-utils"}
types = { path = "crates/types"}
utils = { path = "crates/utils"}

# External dependencies
alloy-sol-types = {version = "0.8.20", features = ["json"]}
alloy-primitives = "0.8.20"


alloy-rpc-types = "=0.9.2"
alloy-contract = "=0.9.2"
alloy-provider = "=0.9.2"
alloy-transport = "=0.9.2"

uniswap_v3_math = { git = "https://github.com/0xKitsune/uniswap-v3-math.git", branch = "main" }
tokio = {version = "1.43.0", features = ["rt-multi-thread"]}
serde = "1.0.217"
serde_json = "1.0.138"
anyhow = "1.0.95"
tracing = "0.1.41"
url = "2.5.4"