[package]
name = "zeus-eth"
version = "0.1.0"
edition = "2021"

[dependencies]
# Local Crates
abi = { path = "crates/abi"}
amm = { path = "crates/amm"}
currency = { path = "crates/currency"}
dapps = { path = "crates/dapps"}
types = { path = "crates/types"}
utils = { path = "crates/utils"}
revm-utils = { path = "crates/revm-utils"}


[dev-dependencies]
tokio = "1"
url = "2"