[package]
name = "zeus-eth"
version = "0.1.0"
edition = "2021"

[dependencies]

alloy-sol-types = {version = "1", features = ["json"]}
alloy-dyn-abi = {version = "1", features = ["eip712"]}
alloy-primitives = "1.3.0"
alloy-signer-local = "1"
alloy-signer = {version = "1", features = ["eip712"]}

alloy-rpc-types = "1"
alloy-contract = "1"
alloy-network = "1"
alloy-provider = {version = "1", features = ["ws"]}
alloy-transport = {version = "1", features = ["throttle"]}
alloy-rpc-client = {version = "1", features = ["reqwest"]}

revm = { version = "28.0.0", features = [
    "std",
    "optional_block_gas_limit",
    "optional_no_base_fee",
    "optional_balance_check",
    "optional_eip3607",
] }

op-revm = { version = " 9.0.0", features = [
    "std",
    "optional_block_gas_limit",
    "optional_no_base_fee",
    "optional_balance_check",
    "optional_eip3607",
] }

rayon = "1.10.0"
tokio = {version = "1", features = ["rt-multi-thread"]}
futures = "0.3"

uniswap_v3_math = { git = "https://github.com/greekfetacheese/uniswap-v3-math.git", branch = "main" }

secure-types = {version = "0.1", features = ["serde"]}


tracing = "0.1"
url = "2"
anyhow = "1"
serde = "1"
serde_json = "1"
thiserror = "2"

[dev-dependencies]
rand = "0.8"