[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }

alloy-sol-types = {version = "1", features = ["json"]}
alloy-dyn-abi = {version = "1.1.0", features = ["eip712"]}
alloy-primitives = "1.1.0"

alloy-rpc-types = "0.15.10"
alloy-contract = "0.15.10"
alloy-provider = {version = "0.15.10", features = ["ws"]}
alloy-network = "0.15.10"
alloy-transport = {version = "0.15.10", features = ["throttle"]}
alloy-rpc-client = {version = "0.15.10", features = ["reqwest"]}

anyhow = "1.0.95"
tracing = "0.1.41"
serde = "1.0.217"
serde_json = "1.0.138"
url = "2.5.4"
tokio = {version = "1.43.0", features = ["rt-multi-thread"]}