[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }

alloy-sol-types = {version = "0.8.20", features = ["json"]}
alloy-primitives = "0.8.20"

alloy-rpc-types = "=0.11.1"
alloy-contract = "=0.11.1"
alloy-provider = "=0.11.1"
alloy-network = "=0.11.1"

anyhow = "1.0.95"


tracing = "0.1.41"
serde = "1.0.217"
url = "2.5.4"
tokio = {version = "1.43.0", features = ["rt-multi-thread"]}