[package]
name = "zeus-token-list"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.117"
image = "0.25.1"
anyhow = "1.0.44"
bincode = "2"
alloy-primitives = "1.2.0"