[package]
name = "zeus-token-list"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "=1.0.219", features = ["derive"] }
serde_json = "=1.0.143"
image = "=0.25.1"
anyhow = "=1.0.99"
bincode = "=2.0.1"
alloy-primitives = "=1.3.1"